services:
  kokoro-fastapi-gpu:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.1
    restart: unless-stopped
    ports:
      - ${KOKORO_PORT:-3000}:8880
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
